[package]
name = "drones2"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23"
rand = "0.9"
rand_xoshiro = "0.7"
arrow = "55.0"
parquet = "55.0"
clap = { version = "4.5", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1